# Generated by Django 5.1.2 on 2024-11-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_reply_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='accepted',
        ),
    ]
