# Generated by Django 5.1.2 on 2024-11-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_remove_reply_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
